#!/bin/bash

##
## Script used with a teracom.cc Ethernet controller TCW121/TCW122
##
## I am not affiliated with teracom.cc, these are scripts I needed 
## for myself that I am releasing in the public domain.
##
## ----------------------------------------------------------------
##
## Creates the RRD db
##

cd `dirname $0`
source ./zz_config

rrdtool create $MONDEVRRD \
    --start now-2years \
    --step 300 \
    DS:d1:GAUGE:300:0:60 \
    DS:d2:GAUGE:300:0:60 \
    DS:v1:GAUGE:300:0:60 \
    DS:v2:GAUGE:300:0:60 \
    DS:t1:GAUGE:300:-40:85 \
    DS:t2:GAUGE:300:-40:85 \
    DS:h1:GAUGE:300:0:100 \
    DS:h2:GAUGE:300:0:100 \
    RRA:AVERAGE:0.5:1:576 \
    RRA:AVERAGE:0.5:6:672 \
    RRA:AVERAGE:0.5:24:732 \
    RRA:AVERAGE:0.5:144:1460

echo CREATED: $MONDEVRRD
